services:
  web:
    container_name: paragliding
    build: .
    expose:
      - 108
    restart: unless-stopped
    networks:
      - venerqueserver

networks:
  venerqueserver:
    external: true
    name: venerqueserver-network
